baseURL = "https://inadequate.solutions"
languageCode = "en-us"

title = "inadequate.solutions"

# https://themes.gohugo.io/hugo-theme-codex/
theme = "wasteland"

#[[menu.nav]]
#    identifier = "posts"
#    name = "posts"
#    url = "/posts"
#    weight = 10
#
#[[menu.nav]]
#    identifier = "projects"
#    name = "projects"
#    url = "/projects"
#    weight = 20
#
[[menu.nav]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    weight = 100
